//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulePublisherCore.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSocial
    {
        public int Id { get; set; }
        public int Userid { get; set; }
        public int SocialId { get; set; }
        public string SocialAccount { get; set; }
    
        public virtual User User { get; set; }
    }
}
